import api from './api';

const FileDownload = require('js-file-download');


// Invoice Types
export const IT_CUSTOMER_BUY_CREDITS = 1;
export const IT_CUSTOMER_BUY_MODELS = 2;

export const closeMenuOnClickOutside = (callback) => {
    const closeMenu = (e) => {
        // if dropdown button clicked (or any its element), ignore the event
        if (e.target.classList.value.indexOf('dropdown-toggle') > -1
                || e.target.parentNode.classList.value.indexOf('dropdown-toggle') > -1) {
            return false;
        }
        callback(false);
    }
    document.body.addEventListener('click', closeMenu);
    return () => document.body.removeEventListener('click', closeMenu);
}

export const downloadFile = (
    download,
    setProgressBar = false
) => {
    api()
        .get('/sanctum/csrf-cookie')
        .then(() => {
            api()({
                method: 'GET',
                url: `/api/v1/products/download/${download.id}`,
                responseType: 'arraybuffer',
                onDownloadProgress: progressEvent => {
                    if (setProgressBar && progressEvent.total > 0) {
                        setProgressBar(Math.round(progressEvent.loaded / progressEvent.total * 100));
                    }
                }
            })
            .then((response) => {
                FileDownload(response.data, download.customer_file_name);
            })
            .catch(error => {
                setProgressBar
                    ? setProgressBar(error.response)
                    : console.error(error.response);
            })
            .finally(() => {
                setTimeout(() => {
                    setProgressBar ? setProgressBar(false) : null;
                }, 5000);
            });
        });
};

// country code: contry name
export const countries = {
    af: "Afghanistan",
    al: "Albania",
    dz: "Algeria",
    as: "American Samoa",
    ad: "Andorra",
    ao: "Angola",
    ai: "Anguilla",
    aq: "Antarctica",
    ag: "Antigua and Barbuda",
    ar: "Argentina",
    am: "Armenia",
    aw: "Aruba",
    au: "Australia",
    at: "Austria",
    az: "Azerbaijan",
    bs: "Bahamas",
    bh: "Bahrain",
    bd: "Bangladesh",
    bb: "Barbados",
    by: "Belarus",
    be: "Belgium",
    bz: "Belize",
    bj: "Benin",
    bm: "Bermuda",
    bt: "Bhutan",
    bo: "Bolivia",
    ba: "Bosnia and Herzegovina",
    bw: "Botswana",
    br: "Brazil",
    io: "British Indian Ocean",
    bn: "Brunei",
    bg: "Bulgaria",
    bf: "Burkina Faso",
    bi: "Burundi",
    kh: "Cambodia",
    cm: "Cameroon",
    ca: "Canada",
    cv: "Cape Verde",
    ky: "Cayman Islands",
    cf: "Central African Republic",
    td: "Chad",
    cl: "Chile",
    cn: "China",
    cx: "Christmas Island",
    cc: "Cocos (Keeling) Islands",
    co: "Colombia",
    km: "Comoros",
    cg: "Congo, Republic of the",
    ck: "Cook Islands",
    cr: "Costa Rica",
    hr: "Croatia",
    cy: "Cyprus",
    cz: "Czech Republic",
    cd: "Democratic Republic of the Congo",
    dk: "Denmark",
    dj: "Djibouti",
    dm: "Dominica",
    do: "Dominican Republic",
    tl: "East Timor",
    ec: "Ecuador",
    eg: "Egypt",
    sv: "El Salvador",
    gq: "Equatorial Guinea",
    er: "Eritrea",
    ee: "Estonia",
    et: "Ethiopia",
    fk: "Falkland Islands (Malvinas)",
    fo: "Faroe Islands",
    fj: "Fiji",
    fi: "Finland",
    fr: "France",
    gf: "French Guiana",
    pf: "French Polynesia",
    ga: "Gabon",
    gm: "Gambia",
    ge: "Georgia",
    de: "Germany",
    gh: "Ghana",
    gi: "Gibraltar",
    gr: "Greece",
    gl: "Greenland",
    gd: "Grenada",
    gp: "Guadeloupe",
    gt: "Guatemala",
    gn: "Guinea",
    gw: "Guinea-Bissau",
    gy: "Guyana",
    ht: "Haiti",
    hn: "Honduras",
    hk: "Hong Kong SAR of China",
    hu: "Hungary",
    is: "Iceland",
    in: "India",
    id: "Indonesia",
    iq: "Iraq",
    ie: "Ireland",
    il: "Israel",
    it: "Italy",
    ci: "Ivory Coast (Côte d'Ivoire)",
    jm: "Jamaica",
    jp: "Japan",
    jo: "Jordan",
    kz: "Kazakhstan",
    ke: "Kenya",
    ki: "Kiribati",
    kr: "Korea, South",
    xk: "Kosovo",
    kw: "Kuwait",
    kg: "Kyrgyzstan",
    la: "Laos",
    lv: "Latvia",
    lb: "Lebanon",
    ls: "Lesotho",
    lr: "Liberia",
    ly: "Libya",
    li: "Liechtenstein",
    lt: "Lithuania",
    lu: "Luxembourg",
    mo: "Macau SAR of China",
    mk: "Macedonia, Republic of",
    mg: "Madagascar",
    mw: "Malawi",
    my: "Malaysia",
    mv: "Maldives",
    ml: "Mali",
    mt: "Malta",
    mh: "Marshall Islands",
    mq: "Martinique",
    mr: "Mauritania",
    mu: "Mauritius",
    yt: "Mayotte",
    mx: "Mexico",
    fm: "Micronesia",
    md: "Moldova",
    mc: "Monaco",
    mn: "Mongolia",
    me: "Montenegro",
    ms: "Montserrat",
    ma: "Morocco",
    mz: "Mozambique",
    mm: "Myanmar",
    na: "Namibia",
    nr: "Nauru",
    np: "Nepal",
    nl: "Netherlands",
    an: "Netherlands Antilles",
    nc: "New Caledonia",
    nz: "New Zealand",
    ni: "Nicaragua",
    ne: "Niger",
    ng: "Nigeria",
    nu: "Niue",
    nf: "Norfolk Island",
    no: "Norway",
    om: "Oman",
    pk: "Pakistan",
    ps: "Palestinian Territory",
    pa: "Panama",
    pg: "Papua New Guinea",
    py: "Paraguay",
    pe: "Peru",
    ph: "Philippines",
    pn: "Pitcairn Island",
    pl: "Poland",
    pt: "Portugal",
    qa: "Qatar",
    re: "Réunion",
    ro: "Romania",
    ru: "Russia",
    rw: "Rwanda",
    sh: "Saint Helena",
    kn: "Saint Kitts and Nevis",
    lc: "Saint Lucia",
    pm: "Saint Pierre and Miquelon",
    vc: "Saint Vincent and the Grenadines",
    ws: "Samoa",
    sm: "San Marino",
    st: "São Tome and Principe",
    sa: "Saudi Arabia",
    sn: "Senegal",
    rs: "Serbia",
    sc: "Seychelles",
    sl: "Sierra Leone",
    sg: "Singapore",
    sk: "Slovakia",
    si: "Slovenia",
    sb: "Solomon Islands",
    so: "Somalia",
    za: "South Africa",
    gs: "South Georgia and the South Sandwich Islands",
    ss: "South Sudan",
    es: "Spain",
    lk: "Sri Lanka",
    sd: "Sudan",
    sr: "Suriname",
    sj: "Svalbard and Jan Mayen",
    sz: "Swaziland",
    se: "Sweden",
    ch: "Switzerland",
    tw: "Taiwan Region",
    tj: "Tajikistan",
    tz: "Tanzania",
    th: "Thailand",
    tg: "Togo",
    tk: "Tokelau",
    to: "Tonga",
    tt: "Trinidad and Tobago",
    tn: "Tunisia",
    tr: "Turkey",
    tm: "Turkmenistan",
    tc: "Turks and Caicos Islands",
    tv: "Tuvalu",
    ug: "Uganda",
    ua: "Ukraine",
    ae: "United Arab Emirates",
    gb: "United Kingdom",
    us: "United States",
    um: "United States Minor Outlying Islands",
    uy: "Uruguay",
    uz: "Uzbekistan",
    vu: "Vanuatu",
    va: "Vatican City",
    ve: "Venezuela",
    vn: "Vietnam",
    vg: "Virgin Islands, British",
    wf: "Wallis and Futuna",
    eh: "Western Sahara",
    ye: "Yemen",
    zm: "Zambia",
    zw: "Zimbabwe",
};